from tkinter import *
root=Tk()
lf = LabelFrame(root, text="Selected Value", width=100, height=80)
lf.place(x=20, y=600, anchor="w")
tx = Text(lf, wrap=WORD, padx=5, height=10, width=50)
tx.insert(INSERT, final_value)
tx.config(state=DISABLED)
scroll = Scrollbar(lf, orient=VERTICAL, command=tx.yview)
scroll.pack(side=RIGHT, fill=Y)
tx.configure(yscrollcommand=scroll.set)
tx.pack()
root.mainloop()